import type { TemplateRecord } from '@/lib/types'

const JAVANESE_GOLD: TemplateRecord = {
  id: 'javanese-gold',
  name: 'Javanese Gold',
  slug: 'javanese-gold',
  category: 'tradisional',
  thumbnail_url: '/templates/javanese-gold/thumbnail.jpg',
  status: 'active',
  sort_order: 1,
  usage_count: 0,
  price: 0,
  required_package: 'all',
  created_at: '2026-01-01T00:00:00.000Z',
  config: {
    meta: {
      name: 'Javanese Gold',
      slug: 'javanese-gold',
      category: 'tradisional',
      color_scheme: {
        primary: '#1a4a1a',
        accent: '#d4af37',
        text: '#ffffff',
        background: '#0f2d0f',
      },
      font: {
        heading: 'Cinzel',
        body: 'Cormorant Garamond',
      },
    },
    loading: {
      background_color: '#1a4a1a',
      text: 'Membuka undangan...',
      animation: 'pulse',
    },
    opening: {
      type: 'fade-reveal',
      duration_ms: 3000,
      music_autoplay: false,
    },
    sections: [
      {
        id: 'hero',
        type: 'hero',
        order: 1,
        enabled: true,
        background: { type: 'color', value: '#1a4a1a' },
        decoration_images: [],
        transition_in: 'fade',
        transition_out: 'slide-up',
        user_fields: ['bride_name', 'groom_name', 'tagline', 'couple_photo_url'],
      },
      {
        id: 'profiles',
        type: 'profiles',
        order: 2,
        enabled: true,
        background: { type: 'color', value: '#0f2d0f' },
        decoration_images: [],
        transition_in: 'fade',
        transition_out: 'slide-up',
        user_fields: ['groom_photo_url', 'bride_photo_url', 'groom_bio', 'bride_bio'],
      },
      {
        id: 'countdown',
        type: 'countdown',
        order: 3,
        enabled: true,
        background: { type: 'color', value: '#0f2d0f' },
        decoration_images: [],
        transition_in: 'slide-up',
        transition_out: 'fade',
        user_fields: ['akad'],
      },
      {
        id: 'events',
        type: 'events',
        order: 4,
        enabled: true,
        background: { type: 'color', value: '#1a4a1a' },
        decoration_images: [],
        transition_in: 'fade',
        transition_out: 'fade',
        user_fields: ['akad', 'resepsi'],
      },
      {
        id: 'story',
        type: 'story',
        order: 5,
        enabled: true,
        background: { type: 'color', value: '#0f2d0f' },
        decoration_images: [],
        transition_in: 'slide-up',
        transition_out: 'fade',
        user_fields: ['story_title', 'story_text', 'couple_photo_url'],
      },
      {
        id: 'gallery',
        type: 'gallery',
        order: 6,
        enabled: true,
        background: { type: 'color', value: '#1a4a1a' },
        decoration_images: [],
        transition_in: 'fade',
        transition_out: 'fade',
        user_fields: ['gallery_photos'],
      },
      {
        id: 'gift',
        type: 'gift',
        order: 7,
        enabled: true,
        background: { type: 'color', value: '#0f2d0f' },
        decoration_images: [],
        transition_in: 'slide-up',
        transition_out: 'fade',
        user_fields: ['gift_accounts'],
      },
      {
        id: 'rsvp',
        type: 'rsvp',
        order: 8,
        enabled: true,
        background: { type: 'color', value: '#1a4a1a' },
        decoration_images: [],
        transition_in: 'fade',
        transition_out: 'fade',
        user_fields: [],
      },
      {
        id: 'wishes',
        type: 'wishes',
        order: 9,
        enabled: true,
        background: { type: 'color', value: '#0f2d0f' },
        decoration_images: [],
        transition_in: 'slide-up',
        transition_out: 'fade',
        user_fields: [],
      },
      {
        id: 'closing',
        type: 'closing',
        order: 10,
        enabled: true,
        background: { type: 'color', value: '#1a4a1a' },
        decoration_images: [],
        transition_in: 'fade',
        transition_out: 'fade',
        user_fields: ['closing_text', 'thank_you_message'],
      },
    ],
  },
}

export default JAVANESE_GOLD
